### ISSUE TITLE
Three.js integration

### ISSUE THREAD

**Issue by timukasr** [edvakf/MMD.js#5]
It is very cool project, but I was wondering if it is possible to use it with Three.js. Or maybe it is possible to convert pmd/vmd files to some format that Three.js loader can open. Any help is appreciated.

**Comment by edvakf** [comment]
I know there are people trying to render MMD models with Three.js such as
http://blog.yktmt.com/2010/12/mmdmodel-on-threejs.html

**Comment by timukasr** [comment]
I checked other solution but it seems that your MMD.js is the only one that support motion. If you have some idea or hints how to reuse your code to make MMD models work in Three.js, then I'd really appreciate some help. There are some common elements (vertices, morphs, materials, bones etc), so maybe it is possible.

**Comment by edvakf** [comment]
Did you check http://www20.atpages.jp/katwat/three.js/examples/mytest10/menu.html ?
I'm not too familiar with Three.js to be able to give advice...
